FROM python:3.9.2

RUN apt update && apt-get install -y \
	gcc \
	default-libmysqlclient-dev \
	python-dev 
	
COPY . .

ENV 'FLASK_TEMPLATE_FOLDER' my_page.html

RUN pip install -r requirements.txt

EXPOSE 81

CMD ["python", "/app/frontend.py"]